import fs from "fs";
import path from "path";
import prettier from "prettier";
import { parse, walk } from "svelte/compiler";
import { totalist } from "totalist";

type ExportName = string;

interface BuildComponentsApi {
	path: string;
}
export interface BuildComponents {
	components: Record<ExportName, BuildComponentsApi>;
	icons: Record<ExportName, BuildComponentsApi>;
}

function parseNested(filepath: string): Set<string> {
	const indexJs = fs.readFileSync(path.join(filepath, "index.ts"), "utf-8");
	const ast = parse(`<script>${indexJs}</script>`);
	const exports = new Set<string>();

	walk(ast as never, {
		enter(node: { type?: string; name?: string; source?: { value?: string } }) {
			if (node.type === "Identifier" && node.name) {
				exports.add(node.name);
			} else if (node.type === "ExportAllDeclaration" && node.source?.value) {
				parseNested(path.join(filepath, node.source.value)).forEach((exportName) => {
					exports.add(exportName);
				});
			}
		},
	});

	return exports;
}

async function componentsFor(
	start: string,
	pathPrefix: string,
): Promise<Record<ExportName, BuildComponentsApi>> {
	const exports = new Set();

	parseNested(start).forEach((exportName) => {
		exports.add(exportName);
	});

	const moduleNames = new Map<ExportName, BuildComponentsApi>();

	await totalist(start, (file) => {
		const moduleName = path.parse(file).name;

		if (exports.has(moduleName)) {
			const path = file;
			moduleNames.set(moduleName, { path: pathPrefix + path });
		}
	});

	const ret: Record<ExportName, BuildComponentsApi> = {};
	[...moduleNames.entries()].sort().forEach(([moduleName, value]) => {
		ret[moduleName] = value;
	});

	return ret;
}

(async () => {
	const components: BuildComponents = {
		components: await componentsFor("./src/lib", "lib/"),
		icons: await componentsFor("./src/lib/icons", "lib/icons/"),
	};

	let code = `// This file is auto-generated by hack/build-components-list.ts
	// Do not edit this file directly

	type KnownComponents = {
		components: Record<string, { path: string }>;
		icons: Record<string, { path: string }>;
	}

	export const Components : KnownComponents = ${JSON.stringify(components, null, 2)};
	`;

	// Read .prettierrc
	const prettierConfig = await prettier.resolveConfig("./.prettierrc");
	if (!prettierConfig) {
		throw new Error("Could not load .prettierrc");
	}
	prettierConfig.parser = "typescript";

	code = await prettier.format(code, prettierConfig);

	fs.writeFileSync("./src/lib/preprocessors/components.ts", code, "utf-8");

	console.log(`Wrote components.ts`);
})();
