// This file is auto-generated by hack/build-components-list.ts
// Do not edit this file directly

type KnownComponents = {
	components: Record<string, { path: string }>;
	icons: Record<string, { path: string }>;
};

export const Components: KnownComponents = {
	components: {
		Accordion: {
			path: "components/Accordion/Accordion.svelte",
		},
		AccordionItem: {
			path: "components/Accordion/AccordionItem.svelte",
		},
		Alert: {
			path: "components/Alert/Alert.svelte",
		},
		Bleed: {
			path: "components/primitives/Bleed/Bleed.svelte",
		},
		BodyLong: {
			path: "components/typography/BodyLong/BodyLong.svelte",
		},
		BodyShort: {
			path: "components/typography/BodyShort/BodyShort.svelte",
		},
		Box: {
			path: "components/primitives/Box/Box.svelte",
		},
		Button: {
			path: "components/Button/Button.svelte",
		},
		Checkbox: {
			path: "components/Checkbox/Checkbox.svelte",
		},
		CheckboxGroup: {
			path: "components/Checkbox/CheckboxGroup.svelte",
		},
		Chips: {
			path: "components/Chips/Chips.svelte",
		},
		ConfirmationPanel: {
			path: "components/ConfirmationPanel/ConfirmationPanel.svelte",
		},
		CopyButton: {
			path: "components/CopyButton/CopyButton.svelte",
		},
		Detail: {
			path: "components/typography/Detail/Detail.svelte",
		},
		ErrorMessage: {
			path: "components/typography/ErrorMessage/ErrorMessage.svelte",
		},
		ErrorSummary: {
			path: "components/ErrorSummary/ErrorSummary.svelte",
		},
		ErrorSummaryItem: {
			path: "components/ErrorSummary/ErrorSummaryItem.svelte",
		},
		Fieldset: {
			path: "components/Fieldset/Fieldset.svelte",
		},
		GuidePanel: {
			path: "components/GuidePanel/GuidePanel.svelte",
		},
		HGrid: {
			path: "components/primitives/HGrid/HGrid.svelte",
		},
		HStack: {
			path: "components/primitives/Stack/HStack.svelte",
		},
		Heading: {
			path: "components/typography/Heading/Heading.svelte",
		},
		HelpText: {
			path: "components/HelpText/HelpText.svelte",
		},
		Hide: {
			path: "components/primitives/Responsive/Hide.svelte",
		},
		Label: {
			path: "components/typography/Label/Label.svelte",
		},
		Link: {
			path: "components/typography/Link/Link.svelte",
		},
		Loader: {
			path: "components/Loader/Loader.svelte",
		},
		Modal: {
			path: "components/Modal/Modal.svelte",
		},
		Page: {
			path: "components/primitives/Page/Page.svelte",
		},
		PageBlock: {
			path: "components/primitives/Page/PageBlock.svelte",
		},
		Pagination: {
			path: "components/Pagination/Pagination.svelte",
		},
		Popover: {
			path: "components/Popover/Popover.svelte",
		},
		RemovableChip: {
			path: "components/Chips/RemovableChip.svelte",
		},
		Search: {
			path: "components/Search/Search.svelte",
		},
		SearchButton: {
			path: "components/Search/SearchButton.svelte",
		},
		Select: {
			path: "components/Select/Select.svelte",
		},
		Show: {
			path: "components/primitives/Responsive/Show.svelte",
		},
		Skeleton: {
			path: "components/Skeleton/Skeleton.svelte",
		},
		Stack: {
			path: "components/primitives/Stack/Stack.svelte",
		},
		Step: {
			path: "components/Stepper/Step.svelte",
		},
		Stepper: {
			path: "components/Stepper/Stepper.svelte",
		},
		Switch: {
			path: "components/Switch/Switch.svelte",
		},
		Tab: {
			path: "components/Tabs/Tab.svelte",
		},
		TabList: {
			path: "components/Tabs/TabList.svelte",
		},
		TabPanel: {
			path: "components/Tabs/TabPanel.svelte",
		},
		Table: {
			path: "components/Table/Table.svelte",
		},
		Tabs: {
			path: "components/Tabs/Tabs.svelte",
		},
		Tag: {
			path: "components/Tag/Tag.svelte",
		},
		Tbody: {
			path: "components/Table/Tbody.svelte",
		},
		Td: {
			path: "components/Table/Td.svelte",
		},
		TextField: {
			path: "components/TextField/TextField.svelte",
		},
		Th: {
			path: "components/Table/Th.svelte",
		},
		Thead: {
			path: "components/Table/Thead.svelte",
		},
		ToggleChip: {
			path: "components/Chips/ToggleChip.svelte",
		},
		ToggleGroup: {
			path: "components/ToggleGroup/ToggleGroup.svelte",
		},
		ToggleGroupItem: {
			path: "components/ToggleGroup/ToggleGroupItem.svelte",
		},
		Tooltip: {
			path: "components/Tooltip/Tooltip.svelte",
		},
		Tr: {
			path: "components/Table/Tr.svelte",
		},
		VStack: {
			path: "components/primitives/Stack/VStack.svelte",
		},
	},
	icons: {
		AirplaneFillIcon: {
			path: "icons/AirplaneFillIcon.svelte",
		},
		AirplaneIcon: {
			path: "icons/AirplaneIcon.svelte",
		},
		AlignBottomFillIcon: {
			path: "icons/AlignBottomFillIcon.svelte",
		},
		AlignBottomIcon: {
			path: "icons/AlignBottomIcon.svelte",
		},
		AlignCenterFillIcon: {
			path: "icons/AlignCenterFillIcon.svelte",
		},
		AlignCenterIcon: {
			path: "icons/AlignCenterIcon.svelte",
		},
		AlignLeftFillIcon: {
			path: "icons/AlignLeftFillIcon.svelte",
		},
		AlignLeftIcon: {
			path: "icons/AlignLeftIcon.svelte",
		},
		AlignMiddleFillIcon: {
			path: "icons/AlignMiddleFillIcon.svelte",
		},
		AlignMiddleIcon: {
			path: "icons/AlignMiddleIcon.svelte",
		},
		AlignRightFillIcon: {
			path: "icons/AlignRightFillIcon.svelte",
		},
		AlignRightIcon: {
			path: "icons/AlignRightIcon.svelte",
		},
		AlignTopFillIcon: {
			path: "icons/AlignTopFillIcon.svelte",
		},
		AlignTopIcon: {
			path: "icons/AlignTopIcon.svelte",
		},
		AllergensFillIcon: {
			path: "icons/AllergensFillIcon.svelte",
		},
		AllergensIcon: {
			path: "icons/AllergensIcon.svelte",
		},
		AngleIcon: {
			path: "icons/AngleIcon.svelte",
		},
		AngleRulerCircleFillIcon: {
			path: "icons/AngleRulerCircleFillIcon.svelte",
		},
		AngleRulerCircleIcon: {
			path: "icons/AngleRulerCircleIcon.svelte",
		},
		AngleRulerTriangleFillIcon: {
			path: "icons/AngleRulerTriangleFillIcon.svelte",
		},
		AngleRulerTriangleIcon: {
			path: "icons/AngleRulerTriangleIcon.svelte",
		},
		ArchiveFillIcon: {
			path: "icons/ArchiveFillIcon.svelte",
		},
		ArchiveIcon: {
			path: "icons/ArchiveIcon.svelte",
		},
		AreaChartFillIcon: {
			path: "icons/AreaChartFillIcon.svelte",
		},
		AreaChartIcon: {
			path: "icons/AreaChartIcon.svelte",
		},
		ArrowCirclepathIcon: {
			path: "icons/ArrowCirclepathIcon.svelte",
		},
		ArrowDownIcon: {
			path: "icons/ArrowDownIcon.svelte",
		},
		ArrowDownRightIcon: {
			path: "icons/ArrowDownRightIcon.svelte",
		},
		ArrowForwardFillIcon: {
			path: "icons/ArrowForwardFillIcon.svelte",
		},
		ArrowForwardIcon: {
			path: "icons/ArrowForwardIcon.svelte",
		},
		ArrowLeftIcon: {
			path: "icons/ArrowLeftIcon.svelte",
		},
		ArrowRedoIcon: {
			path: "icons/ArrowRedoIcon.svelte",
		},
		ArrowRightIcon: {
			path: "icons/ArrowRightIcon.svelte",
		},
		ArrowRightLeftIcon: {
			path: "icons/ArrowRightLeftIcon.svelte",
		},
		ArrowUndoIcon: {
			path: "icons/ArrowUndoIcon.svelte",
		},
		ArrowUpIcon: {
			path: "icons/ArrowUpIcon.svelte",
		},
		ArrowsCirclepathIcon: {
			path: "icons/ArrowsCirclepathIcon.svelte",
		},
		ArrowsSquarepathIcon: {
			path: "icons/ArrowsSquarepathIcon.svelte",
		},
		ArrowsUpDownIcon: {
			path: "icons/ArrowsUpDownIcon.svelte",
		},
		BabyWrappedFillIcon: {
			path: "icons/BabyWrappedFillIcon.svelte",
		},
		BabyWrappedIcon: {
			path: "icons/BabyWrappedIcon.svelte",
		},
		BackpackFillIcon: {
			path: "icons/BackpackFillIcon.svelte",
		},
		BackpackIcon: {
			path: "icons/BackpackIcon.svelte",
		},
		BackwardFillIcon: {
			path: "icons/BackwardFillIcon.svelte",
		},
		BackwardIcon: {
			path: "icons/BackwardIcon.svelte",
		},
		BacteriaFillIcon: {
			path: "icons/BacteriaFillIcon.svelte",
		},
		BacteriaIcon: {
			path: "icons/BacteriaIcon.svelte",
		},
		BagdeFillIcon: {
			path: "icons/BagdeFillIcon.svelte",
		},
		BagdeIcon: {
			path: "icons/BagdeIcon.svelte",
		},
		BaggageFillIcon: {
			path: "icons/BaggageFillIcon.svelte",
		},
		BaggageIcon: {
			path: "icons/BaggageIcon.svelte",
		},
		BandageFillIcon: {
			path: "icons/BandageFillIcon.svelte",
		},
		BandageIcon: {
			path: "icons/BandageIcon.svelte",
		},
		BankNoteFillIcon: {
			path: "icons/BankNoteFillIcon.svelte",
		},
		BankNoteIcon: {
			path: "icons/BankNoteIcon.svelte",
		},
		BarChartFillIcon: {
			path: "icons/BarChartFillIcon.svelte",
		},
		BarChartIcon: {
			path: "icons/BarChartIcon.svelte",
		},
		BedFillIcon: {
			path: "icons/BedFillIcon.svelte",
		},
		BedIcon: {
			path: "icons/BedIcon.svelte",
		},
		BellDotFillIcon: {
			path: "icons/BellDotFillIcon.svelte",
		},
		BellDotIcon: {
			path: "icons/BellDotIcon.svelte",
		},
		BellFillIcon: {
			path: "icons/BellFillIcon.svelte",
		},
		BellIcon: {
			path: "icons/BellIcon.svelte",
		},
		BicycleIcon: {
			path: "icons/BicycleIcon.svelte",
		},
		BoatFillIcon: {
			path: "icons/BoatFillIcon.svelte",
		},
		BoatIcon: {
			path: "icons/BoatIcon.svelte",
		},
		BoneBrokenIcon: {
			path: "icons/BoneBrokenIcon.svelte",
		},
		BoneFillIcon: {
			path: "icons/BoneFillIcon.svelte",
		},
		BoneIcon: {
			path: "icons/BoneIcon.svelte",
		},
		BookFillIcon: {
			path: "icons/BookFillIcon.svelte",
		},
		BookIcon: {
			path: "icons/BookIcon.svelte",
		},
		BookmarkDashIcon: {
			path: "icons/BookmarkDashIcon.svelte",
		},
		BookmarkFillIcon: {
			path: "icons/BookmarkFillIcon.svelte",
		},
		BookmarkIcon: {
			path: "icons/BookmarkIcon.svelte",
		},
		BooksFillIcon: {
			path: "icons/BooksFillIcon.svelte",
		},
		BooksIcon: {
			path: "icons/BooksIcon.svelte",
		},
		BowlFillIcon: {
			path: "icons/BowlFillIcon.svelte",
		},
		BowlIcon: {
			path: "icons/BowlIcon.svelte",
		},
		BrailleFillIcon: {
			path: "icons/BrailleFillIcon.svelte",
		},
		BrailleIcon: {
			path: "icons/BrailleIcon.svelte",
		},
		BranchingIcon: {
			path: "icons/BranchingIcon.svelte",
		},
		BriefcaseClockFillIcon: {
			path: "icons/BriefcaseClockFillIcon.svelte",
		},
		BriefcaseClockIcon: {
			path: "icons/BriefcaseClockIcon.svelte",
		},
		BriefcaseFillIcon: {
			path: "icons/BriefcaseFillIcon.svelte",
		},
		BriefcaseIcon: {
			path: "icons/BriefcaseIcon.svelte",
		},
		BroadcastIcon: {
			path: "icons/BroadcastIcon.svelte",
		},
		BroadcastMinusCircleFillIcon: {
			path: "icons/BroadcastMinusCircleFillIcon.svelte",
		},
		BroadcastMinusCircleIcon: {
			path: "icons/BroadcastMinusCircleIcon.svelte",
		},
		BroadcastPlusCircleFillIcon: {
			path: "icons/BroadcastPlusCircleFillIcon.svelte",
		},
		BroadcastPlusCircleIcon: {
			path: "icons/BroadcastPlusCircleIcon.svelte",
		},
		BubbleChartFillIcon: {
			path: "icons/BubbleChartFillIcon.svelte",
		},
		BubbleChartIcon: {
			path: "icons/BubbleChartIcon.svelte",
		},
		BucketFillIcon: {
			path: "icons/BucketFillIcon.svelte",
		},
		BucketIcon: {
			path: "icons/BucketIcon.svelte",
		},
		BucketMopFillIcon: {
			path: "icons/BucketMopFillIcon.svelte",
		},
		BucketMopIcon: {
			path: "icons/BucketMopIcon.svelte",
		},
		BugFillIcon: {
			path: "icons/BugFillIcon.svelte",
		},
		BugIcon: {
			path: "icons/BugIcon.svelte",
		},
		Buildings2FillIcon: {
			path: "icons/Buildings2FillIcon.svelte",
		},
		Buildings2Icon: {
			path: "icons/Buildings2Icon.svelte",
		},
		Buildings3FillIcon: {
			path: "icons/Buildings3FillIcon.svelte",
		},
		Buildings3Icon: {
			path: "icons/Buildings3Icon.svelte",
		},
		BulletListIcon: {
			path: "icons/BulletListIcon.svelte",
		},
		BusFillIcon: {
			path: "icons/BusFillIcon.svelte",
		},
		BusIcon: {
			path: "icons/BusIcon.svelte",
		},
		CalculatorFillIcon: {
			path: "icons/CalculatorFillIcon.svelte",
		},
		CalculatorIcon: {
			path: "icons/CalculatorIcon.svelte",
		},
		CalendarFillIcon: {
			path: "icons/CalendarFillIcon.svelte",
		},
		CalendarIcon: {
			path: "icons/CalendarIcon.svelte",
		},
		CameraFillIcon: {
			path: "icons/CameraFillIcon.svelte",
		},
		CameraIcon: {
			path: "icons/CameraIcon.svelte",
		},
		CameraTriangleFillIcon: {
			path: "icons/CameraTriangleFillIcon.svelte",
		},
		CameraTriangleIcon: {
			path: "icons/CameraTriangleIcon.svelte",
		},
		CandleFillIcon: {
			path: "icons/CandleFillIcon.svelte",
		},
		CandleIcon: {
			path: "icons/CandleIcon.svelte",
		},
		CaptionsFillIcon: {
			path: "icons/CaptionsFillIcon.svelte",
		},
		CaptionsIcon: {
			path: "icons/CaptionsIcon.svelte",
		},
		CarFillIcon: {
			path: "icons/CarFillIcon.svelte",
		},
		CarIcon: {
			path: "icons/CarIcon.svelte",
		},
		CardFillIcon: {
			path: "icons/CardFillIcon.svelte",
		},
		CardIcon: {
			path: "icons/CardIcon.svelte",
		},
		CaretDownCircleFillIcon: {
			path: "icons/CaretDownCircleFillIcon.svelte",
		},
		CaretDownCircleIcon: {
			path: "icons/CaretDownCircleIcon.svelte",
		},
		CaretDownFillIcon: {
			path: "icons/CaretDownFillIcon.svelte",
		},
		CaretDownIcon: {
			path: "icons/CaretDownIcon.svelte",
		},
		CaretLeftCircleFillIcon: {
			path: "icons/CaretLeftCircleFillIcon.svelte",
		},
		CaretLeftCircleIcon: {
			path: "icons/CaretLeftCircleIcon.svelte",
		},
		CaretLeftFillIcon: {
			path: "icons/CaretLeftFillIcon.svelte",
		},
		CaretLeftIcon: {
			path: "icons/CaretLeftIcon.svelte",
		},
		CaretLeftRightFillIcon: {
			path: "icons/CaretLeftRightFillIcon.svelte",
		},
		CaretLeftRightIcon: {
			path: "icons/CaretLeftRightIcon.svelte",
		},
		CaretRightCircleFillIcon: {
			path: "icons/CaretRightCircleFillIcon.svelte",
		},
		CaretRightCircleIcon: {
			path: "icons/CaretRightCircleIcon.svelte",
		},
		CaretRightFillIcon: {
			path: "icons/CaretRightFillIcon.svelte",
		},
		CaretRightIcon: {
			path: "icons/CaretRightIcon.svelte",
		},
		CaretUpCircleFillIcon: {
			path: "icons/CaretUpCircleFillIcon.svelte",
		},
		CaretUpCircleIcon: {
			path: "icons/CaretUpCircleIcon.svelte",
		},
		CaretUpDownFillIcon: {
			path: "icons/CaretUpDownFillIcon.svelte",
		},
		CaretUpDownFilledDownIcon: {
			path: "icons/CaretUpDownFilledDownIcon.svelte",
		},
		CaretUpDownFilledUpIcon: {
			path: "icons/CaretUpDownFilledUpIcon.svelte",
		},
		CaretUpDownIcon: {
			path: "icons/CaretUpDownIcon.svelte",
		},
		CaretUpFillIcon: {
			path: "icons/CaretUpFillIcon.svelte",
		},
		CaretUpIcon: {
			path: "icons/CaretUpIcon.svelte",
		},
		ChangingRoomFillIcon: {
			path: "icons/ChangingRoomFillIcon.svelte",
		},
		ChangingRoomIcon: {
			path: "icons/ChangingRoomIcon.svelte",
		},
		Chat2FillIcon: {
			path: "icons/Chat2FillIcon.svelte",
		},
		Chat2Icon: {
			path: "icons/Chat2Icon.svelte",
		},
		ChatCheckmarkFillIcon: {
			path: "icons/ChatCheckmarkFillIcon.svelte",
		},
		ChatCheckmarkIcon: {
			path: "icons/ChatCheckmarkIcon.svelte",
		},
		ChatElipsisFillIcon: {
			path: "icons/ChatElipsisFillIcon.svelte",
		},
		ChatElipsisIcon: {
			path: "icons/ChatElipsisIcon.svelte",
		},
		ChatExclamationmarkFillIcon: {
			path: "icons/ChatExclamationmarkFillIcon.svelte",
		},
		ChatExclamationmarkIcon: {
			path: "icons/ChatExclamationmarkIcon.svelte",
		},
		ChatFillIcon: {
			path: "icons/ChatFillIcon.svelte",
		},
		ChatIcon: {
			path: "icons/ChatIcon.svelte",
		},
		CheckmarkCircleFillIcon: {
			path: "icons/CheckmarkCircleFillIcon.svelte",
		},
		CheckmarkCircleIcon: {
			path: "icons/CheckmarkCircleIcon.svelte",
		},
		CheckmarkIcon: {
			path: "icons/CheckmarkIcon.svelte",
		},
		ChefHatFillIcon: {
			path: "icons/ChefHatFillIcon.svelte",
		},
		ChefHatIcon: {
			path: "icons/ChefHatIcon.svelte",
		},
		ChevronDownCircleFillIcon: {
			path: "icons/ChevronDownCircleFillIcon.svelte",
		},
		ChevronDownCircleIcon: {
			path: "icons/ChevronDownCircleIcon.svelte",
		},
		ChevronDownDoubleCircleFillIcon: {
			path: "icons/ChevronDownDoubleCircleFillIcon.svelte",
		},
		ChevronDownDoubleCircleIcon: {
			path: "icons/ChevronDownDoubleCircleIcon.svelte",
		},
		ChevronDownDoubleIcon: {
			path: "icons/ChevronDownDoubleIcon.svelte",
		},
		ChevronDownIcon: {
			path: "icons/ChevronDownIcon.svelte",
		},
		ChevronDownUpIcon: {
			path: "icons/ChevronDownUpIcon.svelte",
		},
		ChevronLeftCircleFillIcon: {
			path: "icons/ChevronLeftCircleFillIcon.svelte",
		},
		ChevronLeftCircleIcon: {
			path: "icons/ChevronLeftCircleIcon.svelte",
		},
		ChevronLeftDoubleCircleFillIcon: {
			path: "icons/ChevronLeftDoubleCircleFillIcon.svelte",
		},
		ChevronLeftDoubleCircleIcon: {
			path: "icons/ChevronLeftDoubleCircleIcon.svelte",
		},
		ChevronLeftDoubleIcon: {
			path: "icons/ChevronLeftDoubleIcon.svelte",
		},
		ChevronLeftFirstCircleFillIcon: {
			path: "icons/ChevronLeftFirstCircleFillIcon.svelte",
		},
		ChevronLeftFirstCircleIcon: {
			path: "icons/ChevronLeftFirstCircleIcon.svelte",
		},
		ChevronLeftFirstIcon: {
			path: "icons/ChevronLeftFirstIcon.svelte",
		},
		ChevronLeftIcon: {
			path: "icons/ChevronLeftIcon.svelte",
		},
		ChevronRightCircleFillIcon: {
			path: "icons/ChevronRightCircleFillIcon.svelte",
		},
		ChevronRightCircleIcon: {
			path: "icons/ChevronRightCircleIcon.svelte",
		},
		ChevronRightDoubleCircleFillIcon: {
			path: "icons/ChevronRightDoubleCircleFillIcon.svelte",
		},
		ChevronRightDoubleCircleIcon: {
			path: "icons/ChevronRightDoubleCircleIcon.svelte",
		},
		ChevronRightDoubleIcon: {
			path: "icons/ChevronRightDoubleIcon.svelte",
		},
		ChevronRightIcon: {
			path: "icons/ChevronRightIcon.svelte",
		},
		ChevronRightLastCircleFillIcon: {
			path: "icons/ChevronRightLastCircleFillIcon.svelte",
		},
		ChevronRightLastCircleIcon: {
			path: "icons/ChevronRightLastCircleIcon.svelte",
		},
		ChevronRightLastIcon: {
			path: "icons/ChevronRightLastIcon.svelte",
		},
		ChevronUpCircleFillIcon: {
			path: "icons/ChevronUpCircleFillIcon.svelte",
		},
		ChevronUpCircleIcon: {
			path: "icons/ChevronUpCircleIcon.svelte",
		},
		ChevronUpDoubleCircleFillIcon: {
			path: "icons/ChevronUpDoubleCircleFillIcon.svelte",
		},
		ChevronUpDoubleCircleIcon: {
			path: "icons/ChevronUpDoubleCircleIcon.svelte",
		},
		ChevronUpDoubleIcon: {
			path: "icons/ChevronUpDoubleIcon.svelte",
		},
		ChevronUpDownIcon: {
			path: "icons/ChevronUpDownIcon.svelte",
		},
		ChevronUpIcon: {
			path: "icons/ChevronUpIcon.svelte",
		},
		ChildEyesFillIcon: {
			path: "icons/ChildEyesFillIcon.svelte",
		},
		ChildEyesIcon: {
			path: "icons/ChildEyesIcon.svelte",
		},
		ChildHairEyesFillIcon: {
			path: "icons/ChildHairEyesFillIcon.svelte",
		},
		ChildHairEyesIcon: {
			path: "icons/ChildHairEyesIcon.svelte",
		},
		CigaretteFillIcon: {
			path: "icons/CigaretteFillIcon.svelte",
		},
		CigaretteIcon: {
			path: "icons/CigaretteIcon.svelte",
		},
		CircleBrokenIcon: {
			path: "icons/CircleBrokenIcon.svelte",
		},
		CircleFillIcon: {
			path: "icons/CircleFillIcon.svelte",
		},
		CircleIcon: {
			path: "icons/CircleIcon.svelte",
		},
		CircleSlashFillIcon: {
			path: "icons/CircleSlashFillIcon.svelte",
		},
		CircleSlashIcon: {
			path: "icons/CircleSlashIcon.svelte",
		},
		ClipboardCheckmarkFillIcon: {
			path: "icons/ClipboardCheckmarkFillIcon.svelte",
		},
		ClipboardCheckmarkIcon: {
			path: "icons/ClipboardCheckmarkIcon.svelte",
		},
		ClipboardFillIcon: {
			path: "icons/ClipboardFillIcon.svelte",
		},
		ClipboardIcon: {
			path: "icons/ClipboardIcon.svelte",
		},
		ClipboardLinkFillIcon: {
			path: "icons/ClipboardLinkFillIcon.svelte",
		},
		ClipboardLinkIcon: {
			path: "icons/ClipboardLinkIcon.svelte",
		},
		ClipboardXMarkFillIcon: {
			path: "icons/ClipboardXMarkFillIcon.svelte",
		},
		ClipboardXMarkIcon: {
			path: "icons/ClipboardXMarkIcon.svelte",
		},
		ClockDashedIcon: {
			path: "icons/ClockDashedIcon.svelte",
		},
		ClockFillIcon: {
			path: "icons/ClockFillIcon.svelte",
		},
		ClockIcon: {
			path: "icons/ClockIcon.svelte",
		},
		ClothingHangerFillIcon: {
			path: "icons/ClothingHangerFillIcon.svelte",
		},
		ClothingHangerIcon: {
			path: "icons/ClothingHangerIcon.svelte",
		},
		CloudDownFillIcon: {
			path: "icons/CloudDownFillIcon.svelte",
		},
		CloudDownIcon: {
			path: "icons/CloudDownIcon.svelte",
		},
		CloudFillIcon: {
			path: "icons/CloudFillIcon.svelte",
		},
		CloudIcon: {
			path: "icons/CloudIcon.svelte",
		},
		CloudSlashFillIcon: {
			path: "icons/CloudSlashFillIcon.svelte",
		},
		CloudSlashIcon: {
			path: "icons/CloudSlashIcon.svelte",
		},
		CloudUpFillIcon: {
			path: "icons/CloudUpFillIcon.svelte",
		},
		CloudUpIcon: {
			path: "icons/CloudUpIcon.svelte",
		},
		CodeIcon: {
			path: "icons/CodeIcon.svelte",
		},
		CoffeeFillIcon: {
			path: "icons/CoffeeFillIcon.svelte",
		},
		CoffeeIcon: {
			path: "icons/CoffeeIcon.svelte",
		},
		CogFillIcon: {
			path: "icons/CogFillIcon.svelte",
		},
		CogIcon: {
			path: "icons/CogIcon.svelte",
		},
		CogRotationFillIcon: {
			path: "icons/CogRotationFillIcon.svelte",
		},
		CogRotationIcon: {
			path: "icons/CogRotationIcon.svelte",
		},
		Combifridge1FillIcon: {
			path: "icons/Combifridge1FillIcon.svelte",
		},
		Combifridge1Icon: {
			path: "icons/Combifridge1Icon.svelte",
		},
		Combifridge2FillIcon: {
			path: "icons/Combifridge2FillIcon.svelte",
		},
		Combifridge2Icon: {
			path: "icons/Combifridge2Icon.svelte",
		},
		CompassFillIcon: {
			path: "icons/CompassFillIcon.svelte",
		},
		CompassIcon: {
			path: "icons/CompassIcon.svelte",
		},
		ComponentFillIcon: {
			path: "icons/ComponentFillIcon.svelte",
		},
		ComponentIcon: {
			path: "icons/ComponentIcon.svelte",
		},
		CurrencyExchangeIcon: {
			path: "icons/CurrencyExchangeIcon.svelte",
		},
		CutleryFillIcon: {
			path: "icons/CutleryFillIcon.svelte",
		},
		CutleryIcon: {
			path: "icons/CutleryIcon.svelte",
		},
		DatabaseFillIcon: {
			path: "icons/DatabaseFillIcon.svelte",
		},
		DatabaseIcon: {
			path: "icons/DatabaseIcon.svelte",
		},
		Density1FillIcon: {
			path: "icons/Density1FillIcon.svelte",
		},
		Density1Icon: {
			path: "icons/Density1Icon.svelte",
		},
		Density2FillIcon: {
			path: "icons/Density2FillIcon.svelte",
		},
		Density2Icon: {
			path: "icons/Density2Icon.svelte",
		},
		Density3Icon: {
			path: "icons/Density3Icon.svelte",
		},
		DiamondFillIcon: {
			path: "icons/DiamondFillIcon.svelte",
		},
		DiamondIcon: {
			path: "icons/DiamondIcon.svelte",
		},
		DishwasherFillIcon: {
			path: "icons/DishwasherFillIcon.svelte",
		},
		DishwasherIcon: {
			path: "icons/DishwasherIcon.svelte",
		},
		DivideIcon: {
			path: "icons/DivideIcon.svelte",
		},
		DocPencilFillIcon: {
			path: "icons/DocPencilFillIcon.svelte",
		},
		DocPencilIcon: {
			path: "icons/DocPencilIcon.svelte",
		},
		DogFillIcon: {
			path: "icons/DogFillIcon.svelte",
		},
		DogHarnessFillIcon: {
			path: "icons/DogHarnessFillIcon.svelte",
		},
		DogHarnessIcon: {
			path: "icons/DogHarnessIcon.svelte",
		},
		DogIcon: {
			path: "icons/DogIcon.svelte",
		},
		DonutChartFillIcon: {
			path: "icons/DonutChartFillIcon.svelte",
		},
		DonutChartIcon: {
			path: "icons/DonutChartIcon.svelte",
		},
		DonutsFillIcon: {
			path: "icons/DonutsFillIcon.svelte",
		},
		DonutsIcon: {
			path: "icons/DonutsIcon.svelte",
		},
		DoorFillIcon: {
			path: "icons/DoorFillIcon.svelte",
		},
		DoorIcon: {
			path: "icons/DoorIcon.svelte",
		},
		DoorOpenFillIcon: {
			path: "icons/DoorOpenFillIcon.svelte",
		},
		DoorOpenIcon: {
			path: "icons/DoorOpenIcon.svelte",
		},
		DownloadIcon: {
			path: "icons/DownloadIcon.svelte",
		},
		DragHorizontalIcon: {
			path: "icons/DragHorizontalIcon.svelte",
		},
		DragVerticalIcon: {
			path: "icons/DragVerticalIcon.svelte",
		},
		EarFillIcon: {
			path: "icons/EarFillIcon.svelte",
		},
		EarIcon: {
			path: "icons/EarIcon.svelte",
		},
		EarSlashFillIcon: {
			path: "icons/EarSlashFillIcon.svelte",
		},
		EarSlashIcon: {
			path: "icons/EarSlashIcon.svelte",
		},
		EarSoundwavesFillIcon: {
			path: "icons/EarSoundwavesFillIcon.svelte",
		},
		EarSoundwavesIcon: {
			path: "icons/EarSoundwavesIcon.svelte",
		},
		EarthFillIcon: {
			path: "icons/EarthFillIcon.svelte",
		},
		EarthIcon: {
			path: "icons/EarthIcon.svelte",
		},
		ElevatorFillIcon: {
			path: "icons/ElevatorFillIcon.svelte",
		},
		ElevatorIcon: {
			path: "icons/ElevatorIcon.svelte",
		},
		EnterIcon: {
			path: "icons/EnterIcon.svelte",
		},
		EnvelopeClosedFillIcon: {
			path: "icons/EnvelopeClosedFillIcon.svelte",
		},
		EnvelopeClosedIcon: {
			path: "icons/EnvelopeClosedIcon.svelte",
		},
		EnvelopeOpenFillIcon: {
			path: "icons/EnvelopeOpenFillIcon.svelte",
		},
		EnvelopeOpenIcon: {
			path: "icons/EnvelopeOpenIcon.svelte",
		},
		EqualsIcon: {
			path: "icons/EqualsIcon.svelte",
		},
		EraserFillIcon: {
			path: "icons/EraserFillIcon.svelte",
		},
		EraserIcon: {
			path: "icons/EraserIcon.svelte",
		},
		EscalatorIcon: {
			path: "icons/EscalatorIcon.svelte",
		},
		EthernetIcon: {
			path: "icons/EthernetIcon.svelte",
		},
		ExclamationmarkIcon: {
			path: "icons/ExclamationmarkIcon.svelte",
		},
		ExclamationmarkTriangleFillIcon: {
			path: "icons/ExclamationmarkTriangleFillIcon.svelte",
		},
		ExclamationmarkTriangleIcon: {
			path: "icons/ExclamationmarkTriangleIcon.svelte",
		},
		ExpandIcon: {
			path: "icons/ExpandIcon.svelte",
		},
		ExternalLinkFillIcon: {
			path: "icons/ExternalLinkFillIcon.svelte",
		},
		ExternalLinkIcon: {
			path: "icons/ExternalLinkIcon.svelte",
		},
		EyeClosedIcon: {
			path: "icons/EyeClosedIcon.svelte",
		},
		EyeFillIcon: {
			path: "icons/EyeFillIcon.svelte",
		},
		EyeIcon: {
			path: "icons/EyeIcon.svelte",
		},
		EyeObfuscatedFillIcon: {
			path: "icons/EyeObfuscatedFillIcon.svelte",
		},
		EyeObfuscatedIcon: {
			path: "icons/EyeObfuscatedIcon.svelte",
		},
		EyeSlashFillIcon: {
			path: "icons/EyeSlashFillIcon.svelte",
		},
		EyeSlashIcon: {
			path: "icons/EyeSlashIcon.svelte",
		},
		EyeWithPupilFillIcon: {
			path: "icons/EyeWithPupilFillIcon.svelte",
		},
		EyeWithPupilIcon: {
			path: "icons/EyeWithPupilIcon.svelte",
		},
		FaceCryFillIcon: {
			path: "icons/FaceCryFillIcon.svelte",
		},
		FaceCryIcon: {
			path: "icons/FaceCryIcon.svelte",
		},
		FaceFillIcon: {
			path: "icons/FaceFillIcon.svelte",
		},
		FaceFrownFillIcon: {
			path: "icons/FaceFrownFillIcon.svelte",
		},
		FaceFrownIcon: {
			path: "icons/FaceFrownIcon.svelte",
		},
		FaceIcon: {
			path: "icons/FaceIcon.svelte",
		},
		FaceLaughFillIcon: {
			path: "icons/FaceLaughFillIcon.svelte",
		},
		FaceLaughIcon: {
			path: "icons/FaceLaughIcon.svelte",
		},
		FaceSmileFillIcon: {
			path: "icons/FaceSmileFillIcon.svelte",
		},
		FaceSmileIcon: {
			path: "icons/FaceSmileIcon.svelte",
		},
		FeedingBottleFillIcon: {
			path: "icons/FeedingBottleFillIcon.svelte",
		},
		FeedingBottleIcon: {
			path: "icons/FeedingBottleIcon.svelte",
		},
		FigureChildFillIcon: {
			path: "icons/FigureChildFillIcon.svelte",
		},
		FigureChildIcon: {
			path: "icons/FigureChildIcon.svelte",
		},
		FigureCombinationFillIcon: {
			path: "icons/FigureCombinationFillIcon.svelte",
		},
		FigureCombinationIcon: {
			path: "icons/FigureCombinationIcon.svelte",
		},
		FigureFillIcon: {
			path: "icons/FigureFillIcon.svelte",
		},
		FigureIcon: {
			path: "icons/FigureIcon.svelte",
		},
		FigureInwardFillIcon: {
			path: "icons/FigureInwardFillIcon.svelte",
		},
		FigureInwardIcon: {
			path: "icons/FigureInwardIcon.svelte",
		},
		FigureOutwardFillIcon: {
			path: "icons/FigureOutwardFillIcon.svelte",
		},
		FigureOutwardIcon: {
			path: "icons/FigureOutwardIcon.svelte",
		},
		FileCheckmarkFillIcon: {
			path: "icons/FileCheckmarkFillIcon.svelte",
		},
		FileCheckmarkIcon: {
			path: "icons/FileCheckmarkIcon.svelte",
		},
		FileCodeFillIcon: {
			path: "icons/FileCodeFillIcon.svelte",
		},
		FileCodeIcon: {
			path: "icons/FileCodeIcon.svelte",
		},
		FileCsvFillIcon: {
			path: "icons/FileCsvFillIcon.svelte",
		},
		FileCsvIcon: {
			path: "icons/FileCsvIcon.svelte",
		},
		FileExcelFillIcon: {
			path: "icons/FileExcelFillIcon.svelte",
		},
		FileExcelIcon: {
			path: "icons/FileExcelIcon.svelte",
		},
		FileExportFillIcon: {
			path: "icons/FileExportFillIcon.svelte",
		},
		FileExportIcon: {
			path: "icons/FileExportIcon.svelte",
		},
		FileFillIcon: {
			path: "icons/FileFillIcon.svelte",
		},
		FileIcon: {
			path: "icons/FileIcon.svelte",
		},
		FileImageFillIcon: {
			path: "icons/FileImageFillIcon.svelte",
		},
		FileImageIcon: {
			path: "icons/FileImageIcon.svelte",
		},
		FileImportFillIcon: {
			path: "icons/FileImportFillIcon.svelte",
		},
		FileImportIcon: {
			path: "icons/FileImportIcon.svelte",
		},
		FileJsonFillIcon: {
			path: "icons/FileJsonFillIcon.svelte",
		},
		FileJsonIcon: {
			path: "icons/FileJsonIcon.svelte",
		},
		FileLoadingFillIcon: {
			path: "icons/FileLoadingFillIcon.svelte",
		},
		FileLoadingIcon: {
			path: "icons/FileLoadingIcon.svelte",
		},
		FileParagraphFillIcon: {
			path: "icons/FileParagraphFillIcon.svelte",
		},
		FileParagraphIcon: {
			path: "icons/FileParagraphIcon.svelte",
		},
		FilePdfFillIcon: {
			path: "icons/FilePdfFillIcon.svelte",
		},
		FilePdfIcon: {
			path: "icons/FilePdfIcon.svelte",
		},
		FilePlusFillIcon: {
			path: "icons/FilePlusFillIcon.svelte",
		},
		FilePlusIcon: {
			path: "icons/FilePlusIcon.svelte",
		},
		FileResetFillIcon: {
			path: "icons/FileResetFillIcon.svelte",
		},
		FileResetIcon: {
			path: "icons/FileResetIcon.svelte",
		},
		FileSearchFillIcon: {
			path: "icons/FileSearchFillIcon.svelte",
		},
		FileSearchIcon: {
			path: "icons/FileSearchIcon.svelte",
		},
		FileShredderFillIcon: {
			path: "icons/FileShredderFillIcon.svelte",
		},
		FileShredderIcon: {
			path: "icons/FileShredderIcon.svelte",
		},
		FileTextFillIcon: {
			path: "icons/FileTextFillIcon.svelte",
		},
		FileTextIcon: {
			path: "icons/FileTextIcon.svelte",
		},
		FileWordFillIcon: {
			path: "icons/FileWordFillIcon.svelte",
		},
		FileWordIcon: {
			path: "icons/FileWordIcon.svelte",
		},
		FileXMarkFillIcon: {
			path: "icons/FileXMarkFillIcon.svelte",
		},
		FileXMarkIcon: {
			path: "icons/FileXMarkIcon.svelte",
		},
		FilesFillIcon: {
			path: "icons/FilesFillIcon.svelte",
		},
		FilesIcon: {
			path: "icons/FilesIcon.svelte",
		},
		FilterIcon: {
			path: "icons/FilterIcon.svelte",
		},
		FingerButtonFillIcon: {
			path: "icons/FingerButtonFillIcon.svelte",
		},
		FingerButtonIcon: {
			path: "icons/FingerButtonIcon.svelte",
		},
		FingerMobileFillIcon: {
			path: "icons/FingerMobileFillIcon.svelte",
		},
		FingerMobileIcon: {
			path: "icons/FingerMobileIcon.svelte",
		},
		FirstAidFillIcon: {
			path: "icons/FirstAidFillIcon.svelte",
		},
		FirstAidIcon: {
			path: "icons/FirstAidIcon.svelte",
		},
		FirstAidKitFillIcon: {
			path: "icons/FirstAidKitFillIcon.svelte",
		},
		FirstAidKitIcon: {
			path: "icons/FirstAidKitIcon.svelte",
		},
		FlagCrossFillIcon: {
			path: "icons/FlagCrossFillIcon.svelte",
		},
		FlagCrossIcon: {
			path: "icons/FlagCrossIcon.svelte",
		},
		FloppydiskFillIcon: {
			path: "icons/FloppydiskFillIcon.svelte",
		},
		FloppydiskIcon: {
			path: "icons/FloppydiskIcon.svelte",
		},
		FlowerFillIcon: {
			path: "icons/FlowerFillIcon.svelte",
		},
		FlowerIcon: {
			path: "icons/FlowerIcon.svelte",
		},
		FlowerPensionFillIcon: {
			path: "icons/FlowerPensionFillIcon.svelte",
		},
		FlowerPensionIcon: {
			path: "icons/FlowerPensionIcon.svelte",
		},
		FlowerPetalFallingFillIcon: {
			path: "icons/FlowerPetalFallingFillIcon.svelte",
		},
		FlowerPetalFallingIcon: {
			path: "icons/FlowerPetalFallingIcon.svelte",
		},
		FlowerPetalsFillIcon: {
			path: "icons/FlowerPetalsFillIcon.svelte",
		},
		FlowerPetalsIcon: {
			path: "icons/FlowerPetalsIcon.svelte",
		},
		FolderFileFillIcon: {
			path: "icons/FolderFileFillIcon.svelte",
		},
		FolderFileIcon: {
			path: "icons/FolderFileIcon.svelte",
		},
		FolderFillIcon: {
			path: "icons/FolderFillIcon.svelte",
		},
		FolderIcon: {
			path: "icons/FolderIcon.svelte",
		},
		FolderMinusFillIcon: {
			path: "icons/FolderMinusFillIcon.svelte",
		},
		FolderMinusIcon: {
			path: "icons/FolderMinusIcon.svelte",
		},
		FolderPlusFillIcon: {
			path: "icons/FolderPlusFillIcon.svelte",
		},
		FolderPlusIcon: {
			path: "icons/FolderPlusIcon.svelte",
		},
		ForkFillIcon: {
			path: "icons/ForkFillIcon.svelte",
		},
		ForkIcon: {
			path: "icons/ForkIcon.svelte",
		},
		ForwardFillIcon: {
			path: "icons/ForwardFillIcon.svelte",
		},
		ForwardIcon: {
			path: "icons/ForwardIcon.svelte",
		},
		FreezerFillIcon: {
			path: "icons/FreezerFillIcon.svelte",
		},
		FreezerIcon: {
			path: "icons/FreezerIcon.svelte",
		},
		FunnelFillIcon: {
			path: "icons/FunnelFillIcon.svelte",
		},
		FunnelIcon: {
			path: "icons/FunnelIcon.svelte",
		},
		GavelFillIcon: {
			path: "icons/GavelFillIcon.svelte",
		},
		GavelIcon: {
			path: "icons/GavelIcon.svelte",
		},
		GavelSoundBlockFillIcon: {
			path: "icons/GavelSoundBlockFillIcon.svelte",
		},
		GavelSoundBlockIcon: {
			path: "icons/GavelSoundBlockIcon.svelte",
		},
		GlassFillIcon: {
			path: "icons/GlassFillIcon.svelte",
		},
		GlassIcon: {
			path: "icons/GlassIcon.svelte",
		},
		GlassesFillIcon: {
			path: "icons/GlassesFillIcon.svelte",
		},
		GlassesIcon: {
			path: "icons/GlassesIcon.svelte",
		},
		GlobeFillIcon: {
			path: "icons/GlobeFillIcon.svelte",
		},
		GlobeIcon: {
			path: "icons/GlobeIcon.svelte",
		},
		GlobeSlashFillIcon: {
			path: "icons/GlobeSlashFillIcon.svelte",
		},
		GlobeSlashIcon: {
			path: "icons/GlobeSlashIcon.svelte",
		},
		HandBandageFillIcon: {
			path: "icons/HandBandageFillIcon.svelte",
		},
		HandBandageIcon: {
			path: "icons/HandBandageIcon.svelte",
		},
		HandFingerFillIcon: {
			path: "icons/HandFingerFillIcon.svelte",
		},
		HandFingerIcon: {
			path: "icons/HandFingerIcon.svelte",
		},
		HandHeartFillIcon: {
			path: "icons/HandHeartFillIcon.svelte",
		},
		HandHeartIcon: {
			path: "icons/HandHeartIcon.svelte",
		},
		HandKnotFilledIcon: {
			path: "icons/HandKnotFilledIcon.svelte",
		},
		HandKnotIcon: {
			path: "icons/HandKnotIcon.svelte",
		},
		HandShakeHeartFillIcon: {
			path: "icons/HandShakeHeartFillIcon.svelte",
		},
		HandShakeHeartIcon: {
			path: "icons/HandShakeHeartIcon.svelte",
		},
		HandshakeFillIcon: {
			path: "icons/HandshakeFillIcon.svelte",
		},
		HandshakeIcon: {
			path: "icons/HandshakeIcon.svelte",
		},
		HangerIcon: {
			path: "icons/HangerIcon.svelte",
		},
		HardHatFillIcon: {
			path: "icons/HardHatFillIcon.svelte",
		},
		HardHatIcon: {
			path: "icons/HardHatIcon.svelte",
		},
		HashtagIcon: {
			path: "icons/HashtagIcon.svelte",
		},
		HatSchoolFillIcon: {
			path: "icons/HatSchoolFillIcon.svelte",
		},
		HatSchoolIcon: {
			path: "icons/HatSchoolIcon.svelte",
		},
		HddDownFillIcon: {
			path: "icons/HddDownFillIcon.svelte",
		},
		HddDownIcon: {
			path: "icons/HddDownIcon.svelte",
		},
		HddUpFillIcon: {
			path: "icons/HddUpFillIcon.svelte",
		},
		HddUpIcon: {
			path: "icons/HddUpIcon.svelte",
		},
		HeadCloudFillIcon: {
			path: "icons/HeadCloudFillIcon.svelte",
		},
		HeadCloudIcon: {
			path: "icons/HeadCloudIcon.svelte",
		},
		HeadFillIcon: {
			path: "icons/HeadFillIcon.svelte",
		},
		HeadHeartFillIcon: {
			path: "icons/HeadHeartFillIcon.svelte",
		},
		HeadHeartIcon: {
			path: "icons/HeadHeartIcon.svelte",
		},
		HeadIcon: {
			path: "icons/HeadIcon.svelte",
		},
		HearingLoopFillIcon: {
			path: "icons/HearingLoopFillIcon.svelte",
		},
		HearingLoopIcon: {
			path: "icons/HearingLoopIcon.svelte",
		},
		HearingLoopRadioFillIcon: {
			path: "icons/HearingLoopRadioFillIcon.svelte",
		},
		HearingLoopRadioIcon: {
			path: "icons/HearingLoopRadioIcon.svelte",
		},
		HeartBrokenFillIcon: {
			path: "icons/HeartBrokenFillIcon.svelte",
		},
		HeartBrokenIcon: {
			path: "icons/HeartBrokenIcon.svelte",
		},
		HeartFillIcon: {
			path: "icons/HeartFillIcon.svelte",
		},
		HeartIcon: {
			path: "icons/HeartIcon.svelte",
		},
		HexagonGridFillIcon: {
			path: "icons/HexagonGridFillIcon.svelte",
		},
		HexagonGridIcon: {
			path: "icons/HexagonGridIcon.svelte",
		},
		HikingTrailSignFillIcon: {
			path: "icons/HikingTrailSignFillIcon.svelte",
		},
		HikingTrailSignIcon: {
			path: "icons/HikingTrailSignIcon.svelte",
		},
		HospitalFillIcon: {
			path: "icons/HospitalFillIcon.svelte",
		},
		HospitalIcon: {
			path: "icons/HospitalIcon.svelte",
		},
		HourglassBottomFilledIcon: {
			path: "icons/HourglassBottomFilledIcon.svelte",
		},
		HourglassIcon: {
			path: "icons/HourglassIcon.svelte",
		},
		HourglassTopFilledIcon: {
			path: "icons/HourglassTopFilledIcon.svelte",
		},
		HouseFillIcon: {
			path: "icons/HouseFillIcon.svelte",
		},
		HouseHeartFillIcon: {
			path: "icons/HouseHeartFillIcon.svelte",
		},
		HouseHeartIcon: {
			path: "icons/HouseHeartIcon.svelte",
		},
		HouseIcon: {
			path: "icons/HouseIcon.svelte",
		},
		ImageFillIcon: {
			path: "icons/ImageFillIcon.svelte",
		},
		ImageIcon: {
			path: "icons/ImageIcon.svelte",
		},
		InboxDownFillIcon: {
			path: "icons/InboxDownFillIcon.svelte",
		},
		InboxDownIcon: {
			path: "icons/InboxDownIcon.svelte",
		},
		InboxFillIcon: {
			path: "icons/InboxFillIcon.svelte",
		},
		InboxIcon: {
			path: "icons/InboxIcon.svelte",
		},
		InboxUpFillIcon: {
			path: "icons/InboxUpFillIcon.svelte",
		},
		InboxUpIcon: {
			path: "icons/InboxUpIcon.svelte",
		},
		InformationIcon: {
			path: "icons/InformationIcon.svelte",
		},
		InformationSquareFillIcon: {
			path: "icons/InformationSquareFillIcon.svelte",
		},
		InformationSquareIcon: {
			path: "icons/InformationSquareIcon.svelte",
		},
		IvFluidBagFillIcon: {
			path: "icons/IvFluidBagFillIcon.svelte",
		},
		IvFluidBagIcon: {
			path: "icons/IvFluidBagIcon.svelte",
		},
		KeyHorizontalFillIcon: {
			path: "icons/KeyHorizontalFillIcon.svelte",
		},
		KeyHorizontalIcon: {
			path: "icons/KeyHorizontalIcon.svelte",
		},
		KeyVerticalFillIcon: {
			path: "icons/KeyVerticalFillIcon.svelte",
		},
		KeyVerticalIcon: {
			path: "icons/KeyVerticalIcon.svelte",
		},
		KnifeFillIcon: {
			path: "icons/KnifeFillIcon.svelte",
		},
		KnifeIcon: {
			path: "icons/KnifeIcon.svelte",
		},
		KronerIcon: {
			path: "icons/KronerIcon.svelte",
		},
		LanguageIcon: {
			path: "icons/LanguageIcon.svelte",
		},
		LaptopFillIcon: {
			path: "icons/LaptopFillIcon.svelte",
		},
		LaptopIcon: {
			path: "icons/LaptopIcon.svelte",
		},
		LaptopTriangleFillIcon: {
			path: "icons/LaptopTriangleFillIcon.svelte",
		},
		LaptopTriangleIcon: {
			path: "icons/LaptopTriangleIcon.svelte",
		},
		LayerMinusFillIcon: {
			path: "icons/LayerMinusFillIcon.svelte",
		},
		LayerMinusIcon: {
			path: "icons/LayerMinusIcon.svelte",
		},
		LayersFillIcon: {
			path: "icons/LayersFillIcon.svelte",
		},
		LayersIcon: {
			path: "icons/LayersIcon.svelte",
		},
		LayersPlusFillIcon: {
			path: "icons/LayersPlusFillIcon.svelte",
		},
		LayersPlusIcon: {
			path: "icons/LayersPlusIcon.svelte",
		},
		LeaveIcon: {
			path: "icons/LeaveIcon.svelte",
		},
		LightBulbFillIcon: {
			path: "icons/LightBulbFillIcon.svelte",
		},
		LightBulbIcon: {
			path: "icons/LightBulbIcon.svelte",
		},
		LightningFillIcon: {
			path: "icons/LightningFillIcon.svelte",
		},
		LightningIcon: {
			path: "icons/LightningIcon.svelte",
		},
		LineGraphDotIcon: {
			path: "icons/LineGraphDotIcon.svelte",
		},
		LineGraphIcon: {
			path: "icons/LineGraphIcon.svelte",
		},
		LineGraphStackedIcon: {
			path: "icons/LineGraphStackedIcon.svelte",
		},
		LinkBrokenIcon: {
			path: "icons/LinkBrokenIcon.svelte",
		},
		LinkIcon: {
			path: "icons/LinkIcon.svelte",
		},
		LocationPinFillIcon: {
			path: "icons/LocationPinFillIcon.svelte",
		},
		LocationPinIcon: {
			path: "icons/LocationPinIcon.svelte",
		},
		MagnifyingGlassFillIcon: {
			path: "icons/MagnifyingGlassFillIcon.svelte",
		},
		MagnifyingGlassIcon: {
			path: "icons/MagnifyingGlassIcon.svelte",
		},
		MeasuringTapeFillIcon: {
			path: "icons/MeasuringTapeFillIcon.svelte",
		},
		MeasuringTapeIcon: {
			path: "icons/MeasuringTapeIcon.svelte",
		},
		MedicineBottleFillIcon: {
			path: "icons/MedicineBottleFillIcon.svelte",
		},
		MedicineBottleIcon: {
			path: "icons/MedicineBottleIcon.svelte",
		},
		MeetingLargeFillIcon: {
			path: "icons/MeetingLargeFillIcon.svelte",
		},
		MeetingLargeIcon: {
			path: "icons/MeetingLargeIcon.svelte",
		},
		MeetingSmallFillIcon: {
			path: "icons/MeetingSmallFillIcon.svelte",
		},
		MeetingSmallIcon: {
			path: "icons/MeetingSmallIcon.svelte",
		},
		MegaphoneFillIcon: {
			path: "icons/MegaphoneFillIcon.svelte",
		},
		MegaphoneIcon: {
			path: "icons/MegaphoneIcon.svelte",
		},
		MegaphoneSpeakingFillIcon: {
			path: "icons/MegaphoneSpeakingFillIcon.svelte",
		},
		MegaphoneSpeakingIcon: {
			path: "icons/MegaphoneSpeakingIcon.svelte",
		},
		MenuElipsisHorizontalCircleFillIcon: {
			path: "icons/MenuElipsisHorizontalCircleFillIcon.svelte",
		},
		MenuElipsisHorizontalCircleIcon: {
			path: "icons/MenuElipsisHorizontalCircleIcon.svelte",
		},
		MenuElipsisHorizontalIcon: {
			path: "icons/MenuElipsisHorizontalIcon.svelte",
		},
		MenuElipsisHorizontalSquareFillIcon: {
			path: "icons/MenuElipsisHorizontalSquareFillIcon.svelte",
		},
		MenuElipsisHorizontalSquareIcon: {
			path: "icons/MenuElipsisHorizontalSquareIcon.svelte",
		},
		MenuElipsisVerticalCircleFillIcon: {
			path: "icons/MenuElipsisVerticalCircleFillIcon.svelte",
		},
		MenuElipsisVerticalCircleIcon: {
			path: "icons/MenuElipsisVerticalCircleIcon.svelte",
		},
		MenuElipsisVerticalIcon: {
			path: "icons/MenuElipsisVerticalIcon.svelte",
		},
		MenuElipsisVerticalSquareFillIcon: {
			path: "icons/MenuElipsisVerticalSquareFillIcon.svelte",
		},
		MenuElipsisVerticalSquareIcon: {
			path: "icons/MenuElipsisVerticalSquareIcon.svelte",
		},
		MenuGridIcon: {
			path: "icons/MenuGridIcon.svelte",
		},
		MenuHamburgerIcon: {
			path: "icons/MenuHamburgerIcon.svelte",
		},
		MicrobeFillIcon: {
			path: "icons/MicrobeFillIcon.svelte",
		},
		MicrobeIcon: {
			path: "icons/MicrobeIcon.svelte",
		},
		MicrophoneFillIcon: {
			path: "icons/MicrophoneFillIcon.svelte",
		},
		MicrophoneIcon: {
			path: "icons/MicrophoneIcon.svelte",
		},
		MicrophoneSlashFillIcon: {
			path: "icons/MicrophoneSlashFillIcon.svelte",
		},
		MicrophoneSlashIcon: {
			path: "icons/MicrophoneSlashIcon.svelte",
		},
		MigrationIcon: {
			path: "icons/MigrationIcon.svelte",
		},
		MinusCircleFillIcon: {
			path: "icons/MinusCircleFillIcon.svelte",
		},
		MinusCircleIcon: {
			path: "icons/MinusCircleIcon.svelte",
		},
		MinusIcon: {
			path: "icons/MinusIcon.svelte",
		},
		MobileFillIcon: {
			path: "icons/MobileFillIcon.svelte",
		},
		MobileIcon: {
			path: "icons/MobileIcon.svelte",
		},
		MobileSmallFillIcon: {
			path: "icons/MobileSmallFillIcon.svelte",
		},
		MobileSmallIcon: {
			path: "icons/MobileSmallIcon.svelte",
		},
		MobileTriangleFillIcon: {
			path: "icons/MobileTriangleFillIcon.svelte",
		},
		MobileTriangleIcon: {
			path: "icons/MobileTriangleIcon.svelte",
		},
		MonitorFillIcon: {
			path: "icons/MonitorFillIcon.svelte",
		},
		MonitorIcon: {
			path: "icons/MonitorIcon.svelte",
		},
		MonitorTriangleFillIcon: {
			path: "icons/MonitorTriangleFillIcon.svelte",
		},
		MonitorTriangleIcon: {
			path: "icons/MonitorTriangleIcon.svelte",
		},
		MoonFillIcon: {
			path: "icons/MoonFillIcon.svelte",
		},
		MoonIcon: {
			path: "icons/MoonIcon.svelte",
		},
		MotorcycleFillIcon: {
			path: "icons/MotorcycleFillIcon.svelte",
		},
		MotorcycleIcon: {
			path: "icons/MotorcycleIcon.svelte",
		},
		MountainFillIcon: {
			path: "icons/MountainFillIcon.svelte",
		},
		MountainIcon: {
			path: "icons/MountainIcon.svelte",
		},
		MugFillIcon: {
			path: "icons/MugFillIcon.svelte",
		},
		MugIcon: {
			path: "icons/MugIcon.svelte",
		},
		MultiplyIcon: {
			path: "icons/MultiplyIcon.svelte",
		},
		NewspaperFillIcon: {
			path: "icons/NewspaperFillIcon.svelte",
		},
		NewspaperIcon: {
			path: "icons/NewspaperIcon.svelte",
		},
		NoSmokingFillIcon: {
			path: "icons/NoSmokingFillIcon.svelte",
		},
		NoSmokingIcon: {
			path: "icons/NoSmokingIcon.svelte",
		},
		NokIcon: {
			path: "icons/NokIcon.svelte",
		},
		NotePencilDashIcon: {
			path: "icons/NotePencilDashIcon.svelte",
		},
		NotePencilFillIcon: {
			path: "icons/NotePencilFillIcon.svelte",
		},
		NotePencilIcon: {
			path: "icons/NotePencilIcon.svelte",
		},
		NumberListIcon: {
			path: "icons/NumberListIcon.svelte",
		},
		OpenSourceFillIcon: {
			path: "icons/OpenSourceFillIcon.svelte",
		},
		OpenSourceIcon: {
			path: "icons/OpenSourceIcon.svelte",
		},
		Over18FillIcon: {
			path: "icons/Over18FillIcon.svelte",
		},
		Over18Icon: {
			path: "icons/Over18Icon.svelte",
		},
		PackageFillIcon: {
			path: "icons/PackageFillIcon.svelte",
		},
		PackageIcon: {
			path: "icons/PackageIcon.svelte",
		},
		PadlockLockedFillIcon: {
			path: "icons/PadlockLockedFillIcon.svelte",
		},
		PadlockLockedIcon: {
			path: "icons/PadlockLockedIcon.svelte",
		},
		PadlockUnlockedFillIcon: {
			path: "icons/PadlockUnlockedFillIcon.svelte",
		},
		PadlockUnlockedIcon: {
			path: "icons/PadlockUnlockedIcon.svelte",
		},
		PaletteFillIcon: {
			path: "icons/PaletteFillIcon.svelte",
		},
		PaletteIcon: {
			path: "icons/PaletteIcon.svelte",
		},
		PaperclipIcon: {
			path: "icons/PaperclipIcon.svelte",
		},
		PaperplaneFillIcon: {
			path: "icons/PaperplaneFillIcon.svelte",
		},
		PaperplaneIcon: {
			path: "icons/PaperplaneIcon.svelte",
		},
		ParagraphIcon: {
			path: "icons/ParagraphIcon.svelte",
		},
		ParasolBeachFillIcon: {
			path: "icons/ParasolBeachFillIcon.svelte",
		},
		ParasolBeachIcon: {
			path: "icons/ParasolBeachIcon.svelte",
		},
		ParkingFillIcon: {
			path: "icons/ParkingFillIcon.svelte",
		},
		ParkingIcon: {
			path: "icons/ParkingIcon.svelte",
		},
		PassportFillIcon: {
			path: "icons/PassportFillIcon.svelte",
		},
		PassportIcon: {
			path: "icons/PassportIcon.svelte",
		},
		PasswordHiddenIcon: {
			path: "icons/PasswordHiddenIcon.svelte",
		},
		PauseFillIcon: {
			path: "icons/PauseFillIcon.svelte",
		},
		PauseIcon: {
			path: "icons/PauseIcon.svelte",
		},
		PencilBoardFillIcon: {
			path: "icons/PencilBoardFillIcon.svelte",
		},
		PencilBoardIcon: {
			path: "icons/PencilBoardIcon.svelte",
		},
		PencilFillIcon: {
			path: "icons/PencilFillIcon.svelte",
		},
		PencilIcon: {
			path: "icons/PencilIcon.svelte",
		},
		PencilLineFillIcon: {
			path: "icons/PencilLineFillIcon.svelte",
		},
		PencilLineIcon: {
			path: "icons/PencilLineIcon.svelte",
		},
		PencilWritingFillIcon: {
			path: "icons/PencilWritingFillIcon.svelte",
		},
		PencilWritingIcon: {
			path: "icons/PencilWritingIcon.svelte",
		},
		PentagonFillIcon: {
			path: "icons/PentagonFillIcon.svelte",
		},
		PentagonIcon: {
			path: "icons/PentagonIcon.svelte",
		},
		PercentIcon: {
			path: "icons/PercentIcon.svelte",
		},
		PersonChatFillIcon: {
			path: "icons/PersonChatFillIcon.svelte",
		},
		PersonChatIcon: {
			path: "icons/PersonChatIcon.svelte",
		},
		PersonCheckmarkFillIcon: {
			path: "icons/PersonCheckmarkFillIcon.svelte",
		},
		PersonCheckmarkIcon: {
			path: "icons/PersonCheckmarkIcon.svelte",
		},
		PersonCircleFillIcon: {
			path: "icons/PersonCircleFillIcon.svelte",
		},
		PersonCircleIcon: {
			path: "icons/PersonCircleIcon.svelte",
		},
		PersonCrossFillIcon: {
			path: "icons/PersonCrossFillIcon.svelte",
		},
		PersonCrossIcon: {
			path: "icons/PersonCrossIcon.svelte",
		},
		PersonEnvelopeFillIcon: {
			path: "icons/PersonEnvelopeFillIcon.svelte",
		},
		PersonEnvelopeIcon: {
			path: "icons/PersonEnvelopeIcon.svelte",
		},
		PersonFillIcon: {
			path: "icons/PersonFillIcon.svelte",
		},
		PersonGavelFillIcon: {
			path: "icons/PersonGavelFillIcon.svelte",
		},
		PersonGavelIcon: {
			path: "icons/PersonGavelIcon.svelte",
		},
		PersonGroupFillIcon: {
			path: "icons/PersonGroupFillIcon.svelte",
		},
		PersonGroupIcon: {
			path: "icons/PersonGroupIcon.svelte",
		},
		PersonHeadsetFillIcon: {
			path: "icons/PersonHeadsetFillIcon.svelte",
		},
		PersonHeadsetIcon: {
			path: "icons/PersonHeadsetIcon.svelte",
		},
		PersonIcon: {
			path: "icons/PersonIcon.svelte",
		},
		PersonMinusFillIcon: {
			path: "icons/PersonMinusFillIcon.svelte",
		},
		PersonMinusIcon: {
			path: "icons/PersonMinusIcon.svelte",
		},
		PersonPencilFillIcon: {
			path: "icons/PersonPencilFillIcon.svelte",
		},
		PersonPencilIcon: {
			path: "icons/PersonPencilIcon.svelte",
		},
		PersonPlusFillIcon: {
			path: "icons/PersonPlusFillIcon.svelte",
		},
		PersonPlusIcon: {
			path: "icons/PersonPlusIcon.svelte",
		},
		PersonPregnantFillIcon: {
			path: "icons/PersonPregnantFillIcon.svelte",
		},
		PersonPregnantIcon: {
			path: "icons/PersonPregnantIcon.svelte",
		},
		PersonRectangleFillIcon: {
			path: "icons/PersonRectangleFillIcon.svelte",
		},
		PersonRectangleIcon: {
			path: "icons/PersonRectangleIcon.svelte",
		},
		PersonSuitFillIcon: {
			path: "icons/PersonSuitFillIcon.svelte",
		},
		PersonSuitIcon: {
			path: "icons/PersonSuitIcon.svelte",
		},
		PersonTallShortFillIcon: {
			path: "icons/PersonTallShortFillIcon.svelte",
		},
		PersonTallShortIcon: {
			path: "icons/PersonTallShortIcon.svelte",
		},
		PhoneFillIcon: {
			path: "icons/PhoneFillIcon.svelte",
		},
		PhoneIcon: {
			path: "icons/PhoneIcon.svelte",
		},
		PieChartFillIcon: {
			path: "icons/PieChartFillIcon.svelte",
		},
		PieChartIcon: {
			path: "icons/PieChartIcon.svelte",
		},
		PiggybankFillIcon: {
			path: "icons/PiggybankFillIcon.svelte",
		},
		PiggybankIcon: {
			path: "icons/PiggybankIcon.svelte",
		},
		PillCircleFillIcon: {
			path: "icons/PillCircleFillIcon.svelte",
		},
		PillCircleIcon: {
			path: "icons/PillCircleIcon.svelte",
		},
		PillCircleRectangleFillIcon: {
			path: "icons/PillCircleRectangleFillIcon.svelte",
		},
		PillCircleRectangleIcon: {
			path: "icons/PillCircleRectangleIcon.svelte",
		},
		PillRectangleFillIcon: {
			path: "icons/PillRectangleFillIcon.svelte",
		},
		PillRectangleIcon: {
			path: "icons/PillRectangleIcon.svelte",
		},
		PinFillIcon: {
			path: "icons/PinFillIcon.svelte",
		},
		PinIcon: {
			path: "icons/PinIcon.svelte",
		},
		PlantFillIcon: {
			path: "icons/PlantFillIcon.svelte",
		},
		PlantIcon: {
			path: "icons/PlantIcon.svelte",
		},
		PlateFillIcon: {
			path: "icons/PlateFillIcon.svelte",
		},
		PlateIcon: {
			path: "icons/PlateIcon.svelte",
		},
		PlayFillIcon: {
			path: "icons/PlayFillIcon.svelte",
		},
		PlayIcon: {
			path: "icons/PlayIcon.svelte",
		},
		PlusCircleFillIcon: {
			path: "icons/PlusCircleFillIcon.svelte",
		},
		PlusCircleIcon: {
			path: "icons/PlusCircleIcon.svelte",
		},
		PlusIcon: {
			path: "icons/PlusIcon.svelte",
		},
		PlusMinusSlashIcon: {
			path: "icons/PlusMinusSlashIcon.svelte",
		},
		PortalFillIcon: {
			path: "icons/PortalFillIcon.svelte",
		},
		PortalIcon: {
			path: "icons/PortalIcon.svelte",
		},
		PresentationFillIcon: {
			path: "icons/PresentationFillIcon.svelte",
		},
		PresentationIcon: {
			path: "icons/PresentationIcon.svelte",
		},
		PrinterLargeFillIcon: {
			path: "icons/PrinterLargeFillIcon.svelte",
		},
		PrinterLargeIcon: {
			path: "icons/PrinterLargeIcon.svelte",
		},
		PrinterLargeTriangleFillIcon: {
			path: "icons/PrinterLargeTriangleFillIcon.svelte",
		},
		PrinterLargeTriangleIcon: {
			path: "icons/PrinterLargeTriangleIcon.svelte",
		},
		PrinterSmallFillIcon: {
			path: "icons/PrinterSmallFillIcon.svelte",
		},
		PrinterSmallIcon: {
			path: "icons/PrinterSmallIcon.svelte",
		},
		PrinterSmallTriangleFillIcon: {
			path: "icons/PrinterSmallTriangleFillIcon.svelte",
		},
		PrinterSmallTriangleIcon: {
			path: "icons/PrinterSmallTriangleIcon.svelte",
		},
		PushPinFillIcon: {
			path: "icons/PushPinFillIcon.svelte",
		},
		PushPinIcon: {
			path: "icons/PushPinIcon.svelte",
		},
		PuzzlePieceFillIcon: {
			path: "icons/PuzzlePieceFillIcon.svelte",
		},
		PuzzlePieceIcon: {
			path: "icons/PuzzlePieceIcon.svelte",
		},
		QrCodeFillIcon: {
			path: "icons/QrCodeFillIcon.svelte",
		},
		QrCodeIcon: {
			path: "icons/QrCodeIcon.svelte",
		},
		QrCodeScanningFillIcon: {
			path: "icons/QrCodeScanningFillIcon.svelte",
		},
		QrCodeScanningIcon: {
			path: "icons/QrCodeScanningIcon.svelte",
		},
		QuestionmarkDiamondFillIcon: {
			path: "icons/QuestionmarkDiamondFillIcon.svelte",
		},
		QuestionmarkDiamondIcon: {
			path: "icons/QuestionmarkDiamondIcon.svelte",
		},
		QuestionmarkIcon: {
			path: "icons/QuestionmarkIcon.svelte",
		},
		QuietZoneFillIcon: {
			path: "icons/QuietZoneFillIcon.svelte",
		},
		QuietZoneIcon: {
			path: "icons/QuietZoneIcon.svelte",
		},
		RaindropFillIcon: {
			path: "icons/RaindropFillIcon.svelte",
		},
		RaindropIcon: {
			path: "icons/RaindropIcon.svelte",
		},
		ReceiptFillIcon: {
			path: "icons/ReceiptFillIcon.svelte",
		},
		ReceiptIcon: {
			path: "icons/ReceiptIcon.svelte",
		},
		ReceptionFillIcon: {
			path: "icons/ReceptionFillIcon.svelte",
		},
		ReceptionIcon: {
			path: "icons/ReceptionIcon.svelte",
		},
		RecordFillIcon: {
			path: "icons/RecordFillIcon.svelte",
		},
		RecordIcon: {
			path: "icons/RecordIcon.svelte",
		},
		RectangleSectionsFillIcon: {
			path: "icons/RectangleSectionsFillIcon.svelte",
		},
		RectangleSectionsIcon: {
			path: "icons/RectangleSectionsIcon.svelte",
		},
		RecycleFillIcon: {
			path: "icons/RecycleFillIcon.svelte",
		},
		RecycleIcon: {
			path: "icons/RecycleIcon.svelte",
		},
		RefrigeratorFillIcon: {
			path: "icons/RefrigeratorFillIcon.svelte",
		},
		RefrigeratorIcon: {
			path: "icons/RefrigeratorIcon.svelte",
		},
		RoadblockFillIcon: {
			path: "icons/RoadblockFillIcon.svelte",
		},
		RoadblockIcon: {
			path: "icons/RoadblockIcon.svelte",
		},
		RobotFillIcon: {
			path: "icons/RobotFillIcon.svelte",
		},
		RobotFrownFillIcon: {
			path: "icons/RobotFrownFillIcon.svelte",
		},
		RobotFrownIcon: {
			path: "icons/RobotFrownIcon.svelte",
		},
		RobotIcon: {
			path: "icons/RobotIcon.svelte",
		},
		RobotSmileFillIcon: {
			path: "icons/RobotSmileFillIcon.svelte",
		},
		RobotSmileIcon: {
			path: "icons/RobotSmileIcon.svelte",
		},
		RocketFillIcon: {
			path: "icons/RocketFillIcon.svelte",
		},
		RocketIcon: {
			path: "icons/RocketIcon.svelte",
		},
		RockingHorseFillIcon: {
			path: "icons/RockingHorseFillIcon.svelte",
		},
		RockingHorseIcon: {
			path: "icons/RockingHorseIcon.svelte",
		},
		RotateLeftFillIcon: {
			path: "icons/RotateLeftFillIcon.svelte",
		},
		RotateLeftIcon: {
			path: "icons/RotateLeftIcon.svelte",
		},
		RotateRightFillIcon: {
			path: "icons/RotateRightFillIcon.svelte",
		},
		RotateRightIcon: {
			path: "icons/RotateRightIcon.svelte",
		},
		RouterIcon: {
			path: "icons/RouterIcon.svelte",
		},
		RulerFillIcon: {
			path: "icons/RulerFillIcon.svelte",
		},
		RulerIcon: {
			path: "icons/RulerIcon.svelte",
		},
		RulersFillIcon: {
			path: "icons/RulersFillIcon.svelte",
		},
		RulersIcon: {
			path: "icons/RulersIcon.svelte",
		},
		SackFillIcon: {
			path: "icons/SackFillIcon.svelte",
		},
		SackIcon: {
			path: "icons/SackIcon.svelte",
		},
		SackKronerFillIcon: {
			path: "icons/SackKronerFillIcon.svelte",
		},
		SackKronerIcon: {
			path: "icons/SackKronerIcon.svelte",
		},
		SackPensionFillIcon: {
			path: "icons/SackPensionFillIcon.svelte",
		},
		SackPensionIcon: {
			path: "icons/SackPensionIcon.svelte",
		},
		SandboxFillIcon: {
			path: "icons/SandboxFillIcon.svelte",
		},
		SandboxIcon: {
			path: "icons/SandboxIcon.svelte",
		},
		ScissorsFillIcon: {
			path: "icons/ScissorsFillIcon.svelte",
		},
		ScissorsIcon: {
			path: "icons/ScissorsIcon.svelte",
		},
		SealCheckmarkFillIcon: {
			path: "icons/SealCheckmarkFillIcon.svelte",
		},
		SealCheckmarkIcon: {
			path: "icons/SealCheckmarkIcon.svelte",
		},
		SealFillIcon: {
			path: "icons/SealFillIcon.svelte",
		},
		SealIcon: {
			path: "icons/SealIcon.svelte",
		},
		SealXMarkFillIcon: {
			path: "icons/SealXMarkFillIcon.svelte",
		},
		SealXMarkIcon: {
			path: "icons/SealXMarkIcon.svelte",
		},
		SectorChartFillIcon: {
			path: "icons/SectorChartFillIcon.svelte",
		},
		SectorChartIcon: {
			path: "icons/SectorChartIcon.svelte",
		},
		ShieldFillIcon: {
			path: "icons/ShieldFillIcon.svelte",
		},
		ShieldIcon: {
			path: "icons/ShieldIcon.svelte",
		},
		ShieldLockFillIcon: {
			path: "icons/ShieldLockFillIcon.svelte",
		},
		ShieldLockIcon: {
			path: "icons/ShieldLockIcon.svelte",
		},
		ShoppingBasketFillIcon: {
			path: "icons/ShoppingBasketFillIcon.svelte",
		},
		ShoppingBasketIcon: {
			path: "icons/ShoppingBasketIcon.svelte",
		},
		ShowerFillIcon: {
			path: "icons/ShowerFillIcon.svelte",
		},
		ShowerIcon: {
			path: "icons/ShowerIcon.svelte",
		},
		ShrinkIcon: {
			path: "icons/ShrinkIcon.svelte",
		},
		SidebarBothFillIcon: {
			path: "icons/SidebarBothFillIcon.svelte",
		},
		SidebarBothIcon: {
			path: "icons/SidebarBothIcon.svelte",
		},
		SidebarLeftFillIcon: {
			path: "icons/SidebarLeftFillIcon.svelte",
		},
		SidebarLeftIcon: {
			path: "icons/SidebarLeftIcon.svelte",
		},
		SidebarRightFillIcon: {
			path: "icons/SidebarRightFillIcon.svelte",
		},
		SidebarRightIcon: {
			path: "icons/SidebarRightIcon.svelte",
		},
		SignLanguageSingleHandFillIcon: {
			path: "icons/SignLanguageSingleHandFillIcon.svelte",
		},
		SignLanguageSingleHandIcon: {
			path: "icons/SignLanguageSingleHandIcon.svelte",
		},
		SignLanguageTwoHandsFillIcon: {
			path: "icons/SignLanguageTwoHandsFillIcon.svelte",
		},
		SignLanguageTwoHandsIcon: {
			path: "icons/SignLanguageTwoHandsIcon.svelte",
		},
		SilhouetteFillIcon: {
			path: "icons/SilhouetteFillIcon.svelte",
		},
		SilhouetteIcon: {
			path: "icons/SilhouetteIcon.svelte",
		},
		SkipBackwardFillIcon: {
			path: "icons/SkipBackwardFillIcon.svelte",
		},
		SkipBackwardIcon: {
			path: "icons/SkipBackwardIcon.svelte",
		},
		SkipForwardFillIcon: {
			path: "icons/SkipForwardFillIcon.svelte",
		},
		SkipForwardIcon: {
			path: "icons/SkipForwardIcon.svelte",
		},
		SnowIcon: {
			path: "icons/SnowIcon.svelte",
		},
		SparkLargeIcon: {
			path: "icons/SparkLargeIcon.svelte",
		},
		SparkSmallIcon: {
			path: "icons/SparkSmallIcon.svelte",
		},
		SparklesFillIcon: {
			path: "icons/SparklesFillIcon.svelte",
		},
		SparklesIcon: {
			path: "icons/SparklesIcon.svelte",
		},
		SpeakerFillIcon: {
			path: "icons/SpeakerFillIcon.svelte",
		},
		SpeakerIcon: {
			path: "icons/SpeakerIcon.svelte",
		},
		SpeakerSlashFillIcon: {
			path: "icons/SpeakerSlashFillIcon.svelte",
		},
		SpeakerSlashIcon: {
			path: "icons/SpeakerSlashIcon.svelte",
		},
		SpeakerSoundWave1FillIcon: {
			path: "icons/SpeakerSoundWave1FillIcon.svelte",
		},
		SpeakerSoundWave1Icon: {
			path: "icons/SpeakerSoundWave1Icon.svelte",
		},
		SpeakerSoundWave2FillIcon: {
			path: "icons/SpeakerSoundWave2FillIcon.svelte",
		},
		SpeakerSoundWave2Icon: {
			path: "icons/SpeakerSoundWave2Icon.svelte",
		},
		SpeakerSoundWave3FillIcon: {
			path: "icons/SpeakerSoundWave3FillIcon.svelte",
		},
		SpeakerSoundWave3Icon: {
			path: "icons/SpeakerSoundWave3Icon.svelte",
		},
		SplitHorizontalFillIcon: {
			path: "icons/SplitHorizontalFillIcon.svelte",
		},
		SplitHorizontalIcon: {
			path: "icons/SplitHorizontalIcon.svelte",
		},
		SplitVerticalFillIcon: {
			path: "icons/SplitVerticalFillIcon.svelte",
		},
		SplitVerticalIcon: {
			path: "icons/SplitVerticalIcon.svelte",
		},
		SpoonFillIcon: {
			path: "icons/SpoonFillIcon.svelte",
		},
		SpoonIcon: {
			path: "icons/SpoonIcon.svelte",
		},
		SquareFillIcon: {
			path: "icons/SquareFillIcon.svelte",
		},
		SquareIcon: {
			path: "icons/SquareIcon.svelte",
		},
		SquarerootIcon: {
			path: "icons/SquarerootIcon.svelte",
		},
		StaircaseIcon: {
			path: "icons/StaircaseIcon.svelte",
		},
		StarFillIcon: {
			path: "icons/StarFillIcon.svelte",
		},
		StarIcon: {
			path: "icons/StarIcon.svelte",
		},
		StarOfLifeFillIcon: {
			path: "icons/StarOfLifeFillIcon.svelte",
		},
		StarOfLifeIcon: {
			path: "icons/StarOfLifeIcon.svelte",
		},
		StarsEuIcon: {
			path: "icons/StarsEuIcon.svelte",
		},
		StethoscopeIcon: {
			path: "icons/StethoscopeIcon.svelte",
		},
		StopFillIcon: {
			path: "icons/StopFillIcon.svelte",
		},
		StopIcon: {
			path: "icons/StopIcon.svelte",
		},
		StrollerFillIcon: {
			path: "icons/StrollerFillIcon.svelte",
		},
		StrollerIcon: {
			path: "icons/StrollerIcon.svelte",
		},
		SunFillIcon: {
			path: "icons/SunFillIcon.svelte",
		},
		SunIcon: {
			path: "icons/SunIcon.svelte",
		},
		TableFillIcon: {
			path: "icons/TableFillIcon.svelte",
		},
		TableIcon: {
			path: "icons/TableIcon.svelte",
		},
		TabletFillIcon: {
			path: "icons/TabletFillIcon.svelte",
		},
		TabletIcon: {
			path: "icons/TabletIcon.svelte",
		},
		TabsAddFillIcon: {
			path: "icons/TabsAddFillIcon.svelte",
		},
		TabsAddIcon: {
			path: "icons/TabsAddIcon.svelte",
		},
		TabsFillIcon: {
			path: "icons/TabsFillIcon.svelte",
		},
		TabsIcon: {
			path: "icons/TabsIcon.svelte",
		},
		TabsRemoveFillIcon: {
			path: "icons/TabsRemoveFillIcon.svelte",
		},
		TabsRemoveIcon: {
			path: "icons/TabsRemoveIcon.svelte",
		},
		TagFillIcon: {
			path: "icons/TagFillIcon.svelte",
		},
		TagIcon: {
			path: "icons/TagIcon.svelte",
		},
		TapWaterFillIcon: {
			path: "icons/TapWaterFillIcon.svelte",
		},
		TapWaterIcon: {
			path: "icons/TapWaterIcon.svelte",
		},
		TasklistFillIcon: {
			path: "icons/TasklistFillIcon.svelte",
		},
		TasklistIcon: {
			path: "icons/TasklistIcon.svelte",
		},
		TasklistSaveFillIcon: {
			path: "icons/TasklistSaveFillIcon.svelte",
		},
		TasklistSaveIcon: {
			path: "icons/TasklistSaveIcon.svelte",
		},
		TasklistSendFillIcon: {
			path: "icons/TasklistSendFillIcon.svelte",
		},
		TasklistSendIcon: {
			path: "icons/TasklistSendIcon.svelte",
		},
		TasklistStartFillIcon: {
			path: "icons/TasklistStartFillIcon.svelte",
		},
		TasklistStartIcon: {
			path: "icons/TasklistStartIcon.svelte",
		},
		TeddyBearFillIcon: {
			path: "icons/TeddyBearFillIcon.svelte",
		},
		TeddyBearIcon: {
			path: "icons/TeddyBearIcon.svelte",
		},
		TenancyFillIcon: {
			path: "icons/TenancyFillIcon.svelte",
		},
		TenancyIcon: {
			path: "icons/TenancyIcon.svelte",
		},
		TerminalFillIcon: {
			path: "icons/TerminalFillIcon.svelte",
		},
		TerminalIcon: {
			path: "icons/TerminalIcon.svelte",
		},
		TestFlaskFillIcon: {
			path: "icons/TestFlaskFillIcon.svelte",
		},
		TestFlaskIcon: {
			path: "icons/TestFlaskIcon.svelte",
		},
		ThermometerFillIcon: {
			path: "icons/ThermometerFillIcon.svelte",
		},
		ThermometerIcon: {
			path: "icons/ThermometerIcon.svelte",
		},
		ThumbDownFillIcon: {
			path: "icons/ThumbDownFillIcon.svelte",
		},
		ThumbDownIcon: {
			path: "icons/ThumbDownIcon.svelte",
		},
		ThumbUpFillIcon: {
			path: "icons/ThumbUpFillIcon.svelte",
		},
		ThumbUpIcon: {
			path: "icons/ThumbUpIcon.svelte",
		},
		TimerFillIcon: {
			path: "icons/TimerFillIcon.svelte",
		},
		TimerIcon: {
			path: "icons/TimerIcon.svelte",
		},
		TimerPauseFillIcon: {
			path: "icons/TimerPauseFillIcon.svelte",
		},
		TimerPauseIcon: {
			path: "icons/TimerPauseIcon.svelte",
		},
		TimerStartFillIcon: {
			path: "icons/TimerStartFillIcon.svelte",
		},
		TimerStartIcon: {
			path: "icons/TimerStartIcon.svelte",
		},
		ToiletFillIcon: {
			path: "icons/ToiletFillIcon.svelte",
		},
		ToiletIcon: {
			path: "icons/ToiletIcon.svelte",
		},
		TokenFillIcon: {
			path: "icons/TokenFillIcon.svelte",
		},
		TokenIcon: {
			path: "icons/TokenIcon.svelte",
		},
		ToothFillIcon: {
			path: "icons/ToothFillIcon.svelte",
		},
		ToothIcon: {
			path: "icons/ToothIcon.svelte",
		},
		TrainFillIcon: {
			path: "icons/TrainFillIcon.svelte",
		},
		TrainIcon: {
			path: "icons/TrainIcon.svelte",
		},
		TramFillIcon: {
			path: "icons/TramFillIcon.svelte",
		},
		TramIcon: {
			path: "icons/TramIcon.svelte",
		},
		TrashFillIcon: {
			path: "icons/TrashFillIcon.svelte",
		},
		TrashIcon: {
			path: "icons/TrashIcon.svelte",
		},
		TrayFoodFillIcon: {
			path: "icons/TrayFoodFillIcon.svelte",
		},
		TrayFoodIcon: {
			path: "icons/TrayFoodIcon.svelte",
		},
		TrendDownIcon: {
			path: "icons/TrendDownIcon.svelte",
		},
		TrendFlatIcon: {
			path: "icons/TrendFlatIcon.svelte",
		},
		TrendUpIcon: {
			path: "icons/TrendUpIcon.svelte",
		},
		TriangleFillIcon: {
			path: "icons/TriangleFillIcon.svelte",
		},
		TriangleIcon: {
			path: "icons/TriangleIcon.svelte",
		},
		TruckFillIcon: {
			path: "icons/TruckFillIcon.svelte",
		},
		TruckIcon: {
			path: "icons/TruckIcon.svelte",
		},
		UmbrellaFillIcon: {
			path: "icons/UmbrellaFillIcon.svelte",
		},
		UmbrellaIcon: {
			path: "icons/UmbrellaIcon.svelte",
		},
		UploadIcon: {
			path: "icons/UploadIcon.svelte",
		},
		VideoFillIcon: {
			path: "icons/VideoFillIcon.svelte",
		},
		VideoIcon: {
			path: "icons/VideoIcon.svelte",
		},
		VideoSlashFillIcon: {
			path: "icons/VideoSlashFillIcon.svelte",
		},
		VideoSlashIcon: {
			path: "icons/VideoSlashIcon.svelte",
		},
		VideoplayerFillIcon: {
			path: "icons/VideoplayerFillIcon.svelte",
		},
		VideoplayerIcon: {
			path: "icons/VideoplayerIcon.svelte",
		},
		VirusFillIcon: {
			path: "icons/VirusFillIcon.svelte",
		},
		VirusIcon: {
			path: "icons/VirusIcon.svelte",
		},
		VitalsIcon: {
			path: "icons/VitalsIcon.svelte",
		},
		WaitingRoomFillIcon: {
			path: "icons/WaitingRoomFillIcon.svelte",
		},
		WaitingRoomIcon: {
			path: "icons/WaitingRoomIcon.svelte",
		},
		WalletFillIcon: {
			path: "icons/WalletFillIcon.svelte",
		},
		WalletIcon: {
			path: "icons/WalletIcon.svelte",
		},
		WateringCanFillIcon: {
			path: "icons/WateringCanFillIcon.svelte",
		},
		WateringCanIcon: {
			path: "icons/WateringCanIcon.svelte",
		},
		WaveformIcon: {
			path: "icons/WaveformIcon.svelte",
		},
		WavesIcon: {
			path: "icons/WavesIcon.svelte",
		},
		WeightIcon: {
			path: "icons/WeightIcon.svelte",
		},
		WheelchairFillIcon: {
			path: "icons/WheelchairFillIcon.svelte",
		},
		WheelchairIcon: {
			path: "icons/WheelchairIcon.svelte",
		},
		WrenchFillIcon: {
			path: "icons/WrenchFillIcon.svelte",
		},
		WrenchIcon: {
			path: "icons/WrenchIcon.svelte",
		},
		XMarkIcon: {
			path: "icons/XMarkIcon.svelte",
		},
		XMarkOctagonFillIcon: {
			path: "icons/XMarkOctagonFillIcon.svelte",
		},
		XMarkOctagonIcon: {
			path: "icons/XMarkOctagonIcon.svelte",
		},
		ZoomMinusFillIcon: {
			path: "icons/ZoomMinusFillIcon.svelte",
		},
		ZoomMinusIcon: {
			path: "icons/ZoomMinusIcon.svelte",
		},
		ZoomPlusFillIcon: {
			path: "icons/ZoomPlusFillIcon.svelte",
		},
		ZoomPlusIcon: {
			path: "icons/ZoomPlusIcon.svelte",
		},
	},
};
